# Based off https://github.com/MinecraftForge/SharedActions/blob/main/.github/workflows/gradle.yml
name: Gradle Building CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle"
        required: false
        type: string
        default: "21"
      gradle_tasks:
        description: "The Gradle task(s) to run for building"
        required: false
        type: string
        default: "build"
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: The AES key to enable Gradle cache encryption
        required: false

permissions:
  contents: read

jobs:
  compute-version:
    uses: ./.github/workflows/gradle.version.yaml

  build:
    needs: [ "compute-version" ]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: "ğŸ“¦ Checkout"
        uses: actions/checkout@v4

      - id: setupJava
        name: "ğŸ”§ Setup Java"
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - id: setupGradle
        name: "ğŸ”§ Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - id: build
        name: "ğŸ—ï¸ Build"
        run: ./gradlew --build-cache ${{ inputs.gradle_tasks }}
        env:
          Version: "${{ needs.compute-version.outputs.version }}"