# Based off https://github.com/MinecraftForge/SharedActions/blob/main/.github/workflows/gradle.yml
name: Gradle Pre-release CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle" # Note: Gradle's Java toolchains feature is used for compiling, which is separate from this
        required: false
        type: string
        default: "21"
      gradle_tasks:
        description: "The Gradle task(s) to run for building"
        required: false
        type: string
        default: "publish"
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: The AES key to enable Gradle cache encryption
        required: false

permissions:
  contents: read
  statuses: write
  packages: write

jobs:
  compute-version:
    name: Compute version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_tag: ${{ steps.version.outputs.version_tag }}
      minecraft_version: ${{ steps.minecraftVersion.outputs.minecraft_version }}
    steps:
      - id: checkout
        name: "ğŸ“¦ Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: minecraftVersion
        name: "ğŸ“¦ Extract Minecraft version"
        run: |
          cat gradle.properties | grep exactMinecraftVersion | cut -d "=" -f 2 > minecraft_version.txt
          echo "Minecraft version: $(cat minecraft_version.txt)"
          echo "minecraft_version=$(cat minecraft_version.txt)" >> "$GITHUB_OUTPUT"

      - id: computeBranchSuffix
        name: "ğŸ”¢ Compute branch suffix"
        if: github.event_name == 'push'
        run: |
          gitRef="${{ github.ref }}"
          branchName=$(echo "${gitRef/refs\/heads\//}")
          echo "Branch name: $branchName"
          
          cleanedBranchName=$(echo $branchName | sed 's/[^a-zA-Z0-9]/-/g')
          echo "Cleaned branch name: $cleanedBranchName"
          
          echo "branch_suffix=$cleanedBranchName" >> "$GITHUB_OUTPUT"

      - id: version
        name: "ğŸ”¢ Compute version"
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          search_commit_body: true
          debug: true
          bump_each_commit: true
          version_format: "${{ steps.minecraftVersion.outputs.minecraft_version }}-${major}.${minor}.${patch}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || format('branch-{0}', steps.computeBranchSuffix.outputs.branch_suffix) }}"

  gradle:
    needs: [ "compute-version" ] # Make sure we now the version before starting to build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: "ğŸ“¦ Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - id: setupJava
        name: "ğŸ”§ Setup Java"
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - id: setupGradle
        name: "ğŸ”§ Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - id: build
        name: "ğŸ—ï¸ Build"
        run: ./gradlew --build-cache ${{ inputs.gradle_tasks }}
        env:
          Version: "${{ needs.compute-version.outputs.version }}"
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ github.actor }}